#ifndef _BALLOON_INTERFACE_STATE_TYPE_HPP
#define _BALLOON_INTERFACE_STATE_TYPE_HPP

namespace dynaman {

	enum class HandState {
		NONCONTACT, HOLD_FINGER_UP, HOLD_FINGER_DOWN
	};

	enum class HoldState {
		FREE,
		TOUCH,
		HELD_INIT,
		HELD_FINGER_UP,
		HELD_FINGER_DOWN
	};
}

#endif // !_BALLOON_INTERFACE_STATE_TYPE_HPP
